apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
spec:
  containers:
  - name: busybox

    image: busybox
    command: ["/bin/sh", "-c"]
    args: ["echo Hello, busybox!; sleep 3600;"]
    env:
    - name: TOKEN
      valueFrom:
        secretKeyRef:
          name: simple-secret
          key: token
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: secret
      mountPath: "/etc/password"
      readOnly: true
  restartPolicy: Always
  volumes:
  - name: secret
    secret:
      secretName: simple-secret
      items:
      - key: password
