apiVersion: batch/v1
kind: Job
metadata:
  name: run-job
  labels:
    name: jobs
spec:
  parallelism: 3
  completions: 10
  template:
    metadata:
      labels:
        name: jobs
    spec:
      containers:
      - name: sleep
        image: busybox
        command: ["sh", "-c", "sleep 5; if [ $((RANDOM % 4)) -eq 0 ]; then exit 1; fi"]
      restartPolicy: Never
